# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='./user/avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='presentation',
            field=models.CharField(max_length=100, null=True, verbose_name='\u4e00\u53e5\u8bdd\u4ecb\u7ecd\u81ea\u5df1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, null=True, verbose_name='\u7528\u6237\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
