# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170418_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
